SUPABASE_URL ="https://sogdnqnhncllvmjifgfx.supabase.co"
SUPABASE_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvZ2RucW5obmNsbHZtamlmZ2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTU4MjIsImV4cCI6MjA3NDIzMTgyMn0.6JuViRYU6IYp0dtW8O8zzptKV_5_g6d9p-6cnlW6kl0"

